import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 11, fontFamily: "Helvetica", color: "#14201A" },
  header: {
    marginBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: "#12503A",
    borderBottomStyle: "solid",
    paddingBottom: 12,
  },
  brand: { fontSize: 18, fontWeight: 700, color: "#12503A" },
  projectLine: { fontSize: 10, color: "#6E7A72", marginTop: 4 },
  title: { fontSize: 16, fontWeight: 700, marginBottom: 2 },
  meta: { fontSize: 9, color: "#6E7A72", marginBottom: 12 },
  sectionLabel: {
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#6E7A72",
    marginTop: 16,
    marginBottom: 6,
  },
  flagsRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 8 },
  flag: {
    fontSize: 9,
    fontWeight: 700,
    backgroundColor: "#F9EDD3",
    color: "#B07A16",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginRight: 6,
    marginBottom: 6,
  },
  progress: { fontSize: 11, lineHeight: 1.5 },
  noteRow: { flexDirection: "row", marginBottom: 6 },
  noteTime: { fontSize: 9, color: "#6E7A72", width: 40 },
  noteText: { fontSize: 10, flex: 1 },
  photosRow: { flexDirection: "row", flexWrap: "wrap" },
  photo: {
    width: 160,
    height: 160,
    objectFit: "cover",
    marginRight: 8,
    marginBottom: 8,
    borderRadius: 4,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 36,
    right: 36,
    fontSize: 8,
    color: "#6E7A72",
    borderTopWidth: 1,
    borderTopColor: "#DBE0D8",
    borderTopStyle: "solid",
    paddingTop: 8,
  },
});

interface DiaryEntryDocumentProps {
  projectName: string;
  contract: string | null;
  postcode: string | null;
  authorName: string;
  day: string;
  reviewed: boolean;
  submittedAt: string;
  flags: string[];
  progress: string;
  notes: { time: string; body: string }[];
  photoUrls: string[];
}

export function DiaryEntryDocument({
  projectName,
  contract,
  postcode,
  authorName,
  day,
  reviewed,
  submittedAt,
  flags,
  progress,
  notes,
  photoUrls,
}: DiaryEntryDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>KnightLog</Text>
          <Text style={styles.projectLine}>
            {projectName}
            {contract ? ` · ${contract}` : ""}
            {postcode ? ` · ${postcode}` : ""}
          </Text>
        </View>

        <Text style={styles.title}>Site Diary — {day}</Text>
        <Text style={styles.meta}>
          Logged by {authorName} · {reviewed ? "Reviewed" : "Not yet reviewed"}
        </Text>

        {flags.length > 0 && (
          <View style={styles.flagsRow}>
            {flags.map((f) => (
              <Text key={f} style={styles.flag}>
                {f}
              </Text>
            ))}
          </View>
        )}

        <Text style={styles.sectionLabel}>Progress</Text>
        <Text style={styles.progress}>{progress}</Text>

        {notes.length > 0 && (
          <>
            <Text style={styles.sectionLabel}>Site notes</Text>
            {notes.map((n, i) => (
              <View key={i} style={styles.noteRow}>
                <Text style={styles.noteTime}>{n.time}</Text>
                <Text style={styles.noteText}>{n.body}</Text>
              </View>
            ))}
          </>
        )}

        {photoUrls.length > 0 && (
          <>
            <Text style={styles.sectionLabel}>Photos</Text>
            <View style={styles.photosRow}>
              {photoUrls.map((url, i) => (
                // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf's Image, not an HTML img
                <Image key={i} src={url} style={styles.photo} />
              ))}
            </View>
          </>
        )}

        <Text style={styles.footer} fixed>
          Submitted {submittedAt} · Generated by KnightLog
        </Text>
      </Page>
    </Document>
  );
}
